dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      user: admin
      pass: admin
      dbname: warehouse
      schema: gold
      threads: 2